### ISSUE TITLE
GAIA download error

### ISSUE THREAD

**Issue by Steinerkadabra** [hutchresearch/Sagitta#1]
Hello!
Thank you very much for providing this tool. I am really interested in working with it!
I tried to run with a FITS file I created (attached) containing the GAIA DR2 identifiers of some sources and the following command:

```
sagitta table1.fits --source_id G --version dr2 —test
```

However, the download unfortunately fails. Here is the complete output:

```
Loading input table
In testing mode!
	Making dataframe from table
Created TAP+ (v1.2.1) - Connection:
	Host: gea.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
Created TAP+ (v1.2.1) - Connection:
	Host: geadata.esac.esa.int
	Use HTTPS: True
	Port: 443
	SSL Port: 443
Downloading missing fields: bp, b, h, l, j, g, k, rp, parallax
Using Gaia DR2
500 Error 500:
null
Traceback (most recent call last):
  File "/Users/thomas/Documents/Projects/temp/venv/bin/sagitta", line 10, in <module>
    sys.exit(main())
  File "/Users/thomas/Documents/Projects/temp/venv/lib/python3.7/site-packages/sagitta/sagitta.py", line 41, in main
    pipeline.download_missing_data()
  File "/Users/thomas/Documents/Projects/temp/venv/lib/python3.7/site-packages/sagitta/sagitta.py", line 262, in download_missing_data
    ver=self.args.version
  File "/Users/thomas/Documents/Projects/temp/venv/lib/python3.7/site-packages/sagitta/data_tools.py", line 149, in download_missing_fields
    verbose = False)
  File "/Users/thomas/Documents/Projects/temp/venv/lib/python3.7/site-packages/astroquery/utils/tap/core.py", line 443, in launch_job_async
    job.get_results()
  File "/Users/thomas/Documents/Projects/temp/venv/lib/python3.7/site-packages/astroquery/utils/tap/model/job.py", line 247, in get_results
    self.__load_async_job_results()
  File "/Users/thomas/Documents/Projects/temp/venv/lib/python3.7/site-packages/astroquery/utils/tap/model/job.py", line 344, in __load_async_job_results
    200)
  File "/Users/thomas/Documents/Projects/temp/venv/lib/python3.7/site-packages/astroquery/utils/tap/conn/tapconn.py", line 635, in check_launch_response_status
    raise requests.exceptions.HTTPError(errMsg)
requests.exceptions.HTTPError: Error 500:
null
```

Is there anything I did wrong?

Thank you very much in advance!

Thomas
[table1.fits.zip](https://github.com/hutchresearch/Sagitta/files/6790463/table1.fits.zip)

**Comment by mkounkel** [comment]
Hi,
In the table, the source_id is formatted as a string, which causes a type issue as it expects a long.
That said, looking at the sources in the table, they are of higher mass than what this pipeline is sensitive to - it only works for stars that can still be considered pre-main sequence

**Comment by Steinerkadabra** [comment]
Hello!
Thank you for the quick response. That indeed resolved the issue. I was not aware that the i need to format the identifiers specifically. Thanks!

I have porpusefully used some stars that are on the main sequence already (beta pic + gamma dor), but also two that are still in the pre-main sequence phase (RS Cha + FU Ori).  I have read the paper and you trained it on lower mass stars, so no wonder it is much more succesfull in classyfing these. It seems to be a great tool for finding K- and M-Type pre-main sequence stars. I am looking forward to working with your tool. Thank you again!

Thomas
