### ISSUE TITLE
AttributeError: 'Column' object has no attribute 'filled'.

### ISSUE THREAD

**Issue by notluquis** [hutchresearch/Sagitta#2]
Hi, I have the following error using Sagitta, with Python 3.12, astropy 6.1.2.

```python
Loading input table
	Making dataframe from table
Traceback (most recent call last):
  File "/Users/notluquis/miniforge3/envs/pymc_env/bin/sagitta", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/notluquis/miniforge3/envs/pymc_env/lib/python3.12/site-packages/sagitta/sagitta.py", line 41, in main
    pipeline.data_frame = DataTools.fix_and_mark_nans(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/notluquis/miniforge3/envs/pymc_env/lib/python3.12/site-packages/sagitta/data_tools.py", line 185, in fix_and_mark_nans
    if data_frame[mask_col_name].any(): data_frame[column] = data_frame[column].filled(nan_replacement)
                                                             ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Column' object has no attribute 'filled'. Did you mean: 'fill'?
```
And I fixed with:

```python
def fix_and_mark_nans(data_frame, nan_column_extension='_nan_mask'):
    """
    1) Replaces the Table's NaN values with boundary values.
    2) Appends a boolean mask to the Table where values were filled in.
        2.1) nan_column_extension is the suffix used in the nan mask columns.
    """
    nan_replacements = {
        "g"         : 20,
        "bp"        : 21,
        "rp"        : 19,
        "j"         : 18,
        "h"         : 18,
        "k"         : 18,
        "parallax"  : 0,
        "av"        : 5,
        "eg"        : 0.1,
        "ebp"       : 0.1,
        "erp"       : 0.1,
        "ej"        : 0.1,
        "eh"        : 0.1,
        "ek"        : 0.1,
        "eparallax" : 2
    }
    
    for column, nan_replacement in nan_replacements.items():
        if column in data_frame.colnames:
            # Create a boolean mask for NaN values
            mask_col_name = column + nan_column_extension
            data_frame[mask_col_name] = np.isnan(data_frame[column])
            
            # Replace NaN values with the specified boundary values
            data_frame[column][np.isnan(data_frame[column])] = nan_replacement
    
    return data_frame
```

**Comment by mkounkel** [comment]
Thanks, I'll look into fixing it - seems like it is a difference between Column and MaskedColumn - the latter has filled method, but most likely would fail with isnan.

**Comment by mkounkel** [comment]
Could you send a version of a table that breaks? I'm not able to replicate the error on my end with any table formatting I commonly run into.

**Comment by notluquis** [comment]
Here's the table. 
[table.fits.zip](https://github.com/user-attachments/files/16568221/table.fits.zip)

**Comment by mkounkel** [comment]
What did you make it with, out of curiosity? I'm not seeing anything unusual about it - this specific table does break the code on my end, but if I were to open it and save it either using astropy.table or in topcat, it runs just fine, same with just having a table of source_ids and letting it download all the necessary photometry.

**Comment by notluquis** [comment]
I made the table using this:
```python
sagitta_data = cluster_data['source_id','parallax','l','b','Gmag','G_BPmag','G_RPmag','j_m','h_m','ks_m',
                            'parallax_error','e_Gmag','e_G_BPmag','e_G_RPmag','j_msigcom','h_msigcom','ks_msigcom']
sagitta_data.rename_columns(sagitta_data.colnames,['source_id','parallax','l','b','g','bp','rp','j','h','k','eparallax','eg','ebp','erp','ej','eh','ek'])
sagitta_data.write('Sagitta/NGC_6383_sagitta.fits',overwrite=True,format='fits')
```

And to clarify, I am using QTable from astropy.table, not Table, but should be the same.

**Comment by mkounkel** [comment]
Got it, and was able to replicate the behavior. I've updated the code to work with both.
